//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Netflix2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public int IdPhim { get; set; }
        public string TieuDe { get; set; }
        public string TenPhim { get; set; }
        public Nullable<System.DateTime> NamSanXuat { get; set; }
        public string TheLoai { get; set; }
        public string ThoiLuong { get; set; }
        public string URLPhim { get; set; }
        public string HinhMinhHoa { get; set; }
        public string ChiTietPhim { get; set; }
        public string DienVien { get; set; }
        public string DaoDien { get; set; }
    }
}
